### ISSUE TITLE
Gerrit support

### ISSUE THREAD

**Issue by damianszczepanik** [ingwarsw/sputnik-maven-plugin#1]
Does it support gerrit or stash only?
If it does - can you provide pom example for gerrit?

**Comment by ingwarsw** [comment]
Yes its also working with gerrit...

As far as i remeber the main thing you need to change is line with goal.

From:
<goal>stash</goal>
To:
<goal>gerrit</goal> 

And also add any extra gerrit configuration options (Your favorite IDE should help you with that)

If needed I can repare full config tomorrow.

**Comment by ingwarsw** [comment]
I created gerrit example in project README.

If you would require any extra information please let me know.
